### PR TITLE
Atlantis local testing PR #1

### PR DESCRIPTION
**Pull request by reulan**
Let's see if the ngrok connection to my local machine works!

### CODE REVIEW

**Comment by ddbotterraform** [comment]
```
Error: This repo is not whitelisted for Atlantis.
```

**Comment by reulan** [comment]
atlantis help

**Comment by ddbotterraform** [comment]
```
Error: This repo is not whitelisted for Atlantis.
```

**Comment by reulan** [comment]
atlantis help

**Comment by ddbotterraform** [comment]
```cmake
atlantis
Terraform For Teams

Usage:
  atlantis <command> [options] -- [terraform options]

Examples:
  # run plan in the root directory passing the -target flag to terraform
  atlantis plan -d . -- -target=resource

  # apply all unapplied plans from this pull request
  atlantis apply

  # apply the plan for the root directory and staging workspace
  atlantis apply -d . -w staging

Commands:
  plan   Runs 'terraform plan' for the changes in this pull request.
         To plan a specific project, use the -d, -w and -p flags.
  apply  Runs 'terraform apply' on all unapplied plans from this pull request.
         To only apply a specific plan, use the -d, -w and -p flags.
  help   View help.

Flags:
  -h, --help   help for atlantis

Use "atlantis [command] --help" for more information about a command.

**Comment by reulan** [comment]
atlantis plan

**Comment by ddbotterraform** [comment]
Ran Plan in dir: `services/atlantis` workspace: `default`

**Plan Error**
```
exit status 127: running "sh -c terraform0.11.8 init -input=false -no-color" in "/Users/msimo/.atlantis/repos/mpmsimo/atlantest/1/default/services/atlantis"
sh: terraform0.11.8: command not found

```

**Comment by ddbotterraform** [comment]
Ran Plan in dir: `services/atlantis` workspace: `default`

```diff

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d services/atlantis`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.ddops.cool/lock?id=mpmsimo%252Fatlantest%252Fservices%252Fatlantis%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d services/atlantis`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by reulan** [comment]
atlantis apply

**Comment by ddbotterraform** [comment]
Ran Apply for 0 projects:

**Comment by reulan** [comment]
atlantis plan

**Comment by reulan** [comment]
atlantis plan

**Comment by reulan** [comment]
atlantis plan

**Comment by ddbotterraform** [comment]
**Warning**: The plan for dir: `services/atlantis` workspace: `default` was **discarded** via the Atlantis UI.

To `apply` this plan you must run `plan` again.

**Comment by ddbotterraform** [comment]
**Warning**: The plan for dir: `services/atlantis` workspace: `default` was **discarded** via the Atlantis UI.

To `apply` this plan you must run `plan` again.

**Comment by reulan** [comment]
atlantis plan

**Comment by ddbotterraform** [comment]
Ran Plan in dir: `services/atlantis` workspace: `default`

```diff

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d services/atlantis`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis-test.ddops.cool/lock?id=dronedeploy%252Fatlantest%252Fservices%252Fatlantis%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d services/atlantis`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by reulan** [comment]
atlantis apply

**Comment by ddbotterraform** [comment]
Ran Apply for 0 projects:

**Comment by ddbotterraform** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `services/atlantis` workspace: `default`

**Pull request merged**
