### PR TITLE
Update the variable name

### PR DESCRIPTION
**Pull request by reulan**

### CODE REVIEW

**Comment by ddbotterraform** [comment]
Ran Plan in dir: `services/atlantis` workspace: `default`

```diff

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d services/atlantis`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis-test.ddops.cool/lock?id=dronedeploy%252Fatlantest%252Fservices%252Fatlantis%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d services/atlantis`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by reulan** [comment]
atlantis plan

**Comment by ddbotterraform** [comment]
Ran Plan in dir: `services/atlantis` workspace: `default`

```diff

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d services/atlantis`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis-test.ddops.cool/lock?id=dronedeploy%252Fatlantest%252Fservices%252Fatlantis%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d services/atlantis`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by reulan** [comment]
atlantis apply

**Comment by ddbotterraform** [comment]
Ran Apply for 0 projects:

**Comment by reulan** [comment]
atlantis plan

**Comment by ddbotterraform** [comment]
Ran Plan in dir: `services/atlantis` workspace: `default`

```diff

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d services/atlantis`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis-test.ddops.cool/lock?id=dronedeploy%252Fatlantest%252Fservices%252Fatlantis%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d services/atlantis`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Pull request closed without merging**
